changed files so that it (the original master) actually compiles
eat.c line 33 and pickup.c (can't remember line number, but you could fix eat.c and try and compile and it will error out at that line number)
dnethackW.zip is bunk (meaning it's the REALLY old version) dnethack.zip is the updated compiled version for windows tty.

still errors with compile though....lots and lots and lots of objects in wall errors.....and then this:

../util/panic.c:54:7: warning: conflicting types for built-in function 'alloca'
 long *alloca(cnt)
       ^
../src/attrib.c: In function 'init_mask_attr':
../src/attrib.c:613:23: warning: initialization discards 'const' qualifier from
pointer target type
  struct Role *mrole = pm2role(mask->mp->mskrolenum);
                       ^
In file included from ../include/config.h:248:0,
                 from ../include/hack.h:9,
                 from ../src/mon.c:10:
../src/mon.c:59:25: warning: conflicting types for built-in function 'pow'
 STATIC_DCL double FDECL(pow,